#!/bin/bash -i
# DISPLAY DEPENDENCY VERSIONS INSTALLED ON THE SYSTEM

set -o errexit  # ABORT ON NON-ZERO EXIT STATUS
set -o pipefail # DON'T HIDE ERRORS WITHIN PIPES

# CONSTANTS
readonly ARGS=( "${@}" )
readonly SEPARATOR=$(printf "%.s#" {1..75})
readonly OUTPUT_FILE="/tmp/versions.md"
readonly -A EXCLUDE_IN_OUTPUT_MODE=(["Java DEV VM"]=1 ["Kernel"]=1 ["Docker Server"]=1 ["Kubectl Server"]=1)
readonly -A ICONS_IN_OUTPUT_MODE=(["System"]=":computer:" \
  ["Apps"]=":robot:" \
  ["Version Control System"]=":herb:" \
  ["Java"]=":coffee:" \
  ["JavaScript"]=":electron:" \
  ["Python"]=":snake:" \
  ["Cloud"]=":cloud:")
readonly -A URLS_IN_OUTPUT_MODE=(["Ubuntu"]="https://wiki.ubuntu.com/Releases" \
  ["Kitty Terminal"]="https://github.com/kovidgoyal/kitty/releases" \
  ["Firefox"]="https://www.mozilla.org/en-US/firefox/releases/" \
  ["Betterfox"]="https://github.com/yokoffing/Betterfox/releases" \
  ["IntelliJ IDEA"]="https://www.jetbrains.com/idea/whatsnew/" \
  ["DBeaver"]="https://github.com/dbeaver/dbeaver/releases" \
  ["Postman"]="https://www.postman.com/release-notes/postman-app/" \
  ["Keystore Explorer"]="https://github.com/kaikramer/keystore-explorer/releases" \
  ["Git"]="https://git-scm.com/downloads" \
  ["Git Filter-Repo"]="https://github.com/newren/git-filter-repo/releases" \
  ["Git LFS"]="https://github.com/git-lfs/git-lfs/releases" \
  ["GitHub CLI"]="https://github.com/cli/cli/releases" \
  ["Java LTS"]="https://www.java.com/releases/" \
  ["Java STS"]="https://www.java.com/releases/" \
  ["SDKMan"]="https://github.com/sdkman/sdkman-cli/releases" \
  ["Maven"]="https://maven.apache.org/docs/history.html" \
  ["Spring Boot CLI"]="https://github.com/spring-projects/spring-boot/releases" \
  ["Async Profiler"]="https://github.com/async-profiler/async-profiler/releases" \
  ["Kafka"]="https://kafka.apache.org/downloads" \
  ["Node"]="https://github.com/nodejs/node/releases" \
  ["Corepack"]="https://github.com/nodejs/corepack/releases" \
  ["Npm"]="https://github.com/npm/cli/releases" \
  ["Pnpm"]="https://github.com/pnpm/pnpm/releases" \
  ["Yarn"]="https://github.com/yarnpkg/berry/releases" \
  ["Gulp CLI"]="https://github.com/gulpjs/gulp-cli/releases" \
  ["Python"]="https://docs.python.org/3/whatsnew/changelog.html" \
  ["Pipx"]="https://github.com/pypa/pipx/releases" \
  ["VirtualEnv"]="https://github.com/pypa/virtualenv/releases" \
  ["Go"]="https://go.dev/doc/devel/release" \
  ["Docker"]="https://github.com/moby/moby/releases" \
  ["Docker Buildx"]="https://github.com/docker/buildx/releases" \
  ["Docker Compose"]="https://github.com/docker/compose/releases" \
  ["Docker Scout"]="https://github.com/docker/scout-cli/releases" \
  ["Kubectl"]="https://github.com/kubernetes/kubernetes/releases" \
  ["Kubectl Krew"]="https://github.com/kubernetes-sigs/krew/releases" \
  ["K3d"]="https://github.com/k3d-io/k3d/releases" \
  ["K3s"]="https://github.com/k3s-io/k3s/releases" \
  ["Helm"]="https://github.com/helm/helm/releases")
# COLORS
readonly RESET="\033[0m"
readonly GREEN="\033[1;32m"
readonly YELLOW="\033[1;33m"

main() {
  options "${ARGS[@]}"
  logTitle
  logSection "System"
  logVersion "Java DEV VM" "$(getJavaDevVmVersion)"
  logVersion "Ubuntu" "$(getUbuntuVersion)"
  logVersion "Kernel" "$(getKernelVersion)"
  logVersion "Kitty Terminal" "$(getKittyVersion)"
  logVersion "Firefox" "$(getFirefoxVersion)"
  logVersion "Betterfox" "$(getBetterfoxVersion)"
  logSection "Apps"
  logVersion "IntelliJ IDEA" "$(getIntellijIdeaVersion)"
  logVersion "DBeaver" "$(getDBeaverVersion)"
  logVersion "Postman" "$(getPostmanVersion)"
  logVersion "Keystore Explorer" "$(getKeystoreExplorerVersion)"
  logSection "Version Control System"
  logVersion "Git" "$(getGitVersion)"
  logVersion "Git Filter-Repo" "$(getGitFilterRepoVersion)"
  logVersion "Git LFS" "$(getGitLfsVersion)"
  logVersion "GitHub CLI" "$(getGitHubCliVersion)"
  logSection "Java"
  logVersion "Java LTS" "$(getJavaLtsVersion)"
  logVersion "Java STS" "$(getJavaStsVersion)"
  logVersion "SDKMan" "$(getSDKManVersion)"
  logVersion "Maven" "$(getSDKManDependencyVersion "maven")"
  logVersion "Spring Boot CLI" "$(getSDKManDependencyVersion "springboot")"
  logVersion "Async Profiler" "$(getAsyncProfilerVersion)"
  logVersion "Kafka" "$(getKafkaVersion)"
  logSection "JavaScript"
  logVersion "Node" "$(getNodeVersion)"
  logVersion "Corepack" "$(getCorepackVersion)"
  logVersion "Npm" "$(getNpmVersion)"
  logVersion "Pnpm" "$(getPnpmVersion)"
  logVersion "Yarn" "$(getYarnVersion)"
  logVersion "Gulp CLI" "$(getGulpCliVersion)"
  logSection "Python"
  logVersion "Python" "$(getPythonVersion)"
  logVersion "Pipx" "$(getPipxVersion)"
  logVersion "VirtualEnv" "$(getVirtualEnvVersion)"
  logSection "Cloud"
  logVersion "Go" "$(getGoVersion)"
  logVersion "Docker Client" "$(getDockerClientVersion)"
  logVersion "Docker Server" "$(getDockerServerVersion)"
  logVersion "Docker Buildx" "$(getDockerBuildxVersion)"
  logVersion "Docker Compose" "$(getDockerComposeVersion)"
  logVersion "Docker Scout" "$(getDockerScoutVersion)"
  logVersion "Kubectl Client" "$(getKubectlClientVersion)"
  logVersion "Kubectl Server" "$(getKubectlServerVersion)"
  logVersion "Kubectl Krew" "$(getKubectlKrewVersion)"
  logVersion "K3d" "$(getK3dVersion)"
  logVersion "Helm" "$(getHelmVersion)"
  logSeparator
  if [[ "${OUTPUT_MODE}" == "true" ]]; then
    printf "Versions saved to: %s\n" "${OUTPUT_FILE}"
  fi
}

options() {
  while (( ${#} > 0 )); do
    case "${1}" in
      -o | --output) readonly OUTPUT_MODE="true";;
      *) help;;
    esac
    shift
  done
}

help() {
  cat << EOF
Usage: ${0}

Display dependency versions installed on the system
EOF
  exit 1
}

logTitle() {
  if [[ "${OUTPUT_MODE}" == "true" ]]; then
    printf "## Versions\n" > "${OUTPUT_FILE}"
  fi
}

logSection() {
  local sectionName="${1}"
  if [[ "${OUTPUT_MODE}" == "true" ]]; then
    printf "\n### %s %s\n" "${ICONS_IN_OUTPUT_MODE[${sectionName}]}" "${sectionName}" >> "${OUTPUT_FILE}"
  else
    logSeparator
    printf "%b#%b %b%-71s%b %b#%b\n" \
      "${YELLOW}" "${RESET}" \
      "${GREEN}" "${sectionName^^}" "${RESET}"\
      "${YELLOW}" "${RESET}"
    logSeparator
  fi
}

logSeparator() {
  if [[ "${OUTPUT_MODE}" != "true" ]]; then
    printf "%b%s%b\n" "${YELLOW}" "${SEPARATOR}" "${RESET}"
  fi
}

logVersion() {
  local dependency="${1}"
  if [[ "${OUTPUT_MODE}" == "true" ]]; then
    if [[ ! ${EXCLUDE_IN_OUTPUT_MODE[${1}]} ]]; then
      if [[ "${dependency}" == *" Client" ]]; then
        dependency="${dependency% Client}"
      fi
      if [[ ${URLS_IN_OUTPUT_MODE[${dependency}]} ]]; then
        if [[ "${dependency}" == "K3d" ]]; then
          printf -- "- [%s](%s) ([K3s](%s)) **%s**\n" "${dependency}" "${URLS_IN_OUTPUT_MODE[${dependency}]}" "${URLS_IN_OUTPUT_MODE['K3s']}" "${2}" >> "${OUTPUT_FILE}"
        else
          printf -- "- [%s](%s) **%s**\n" "${dependency}" "${URLS_IN_OUTPUT_MODE[${dependency}]}" "${2}" >> "${OUTPUT_FILE}"
        fi
      else
        printf -- "- %s **%s**\n" "${dependency}" "${2}" >> "${OUTPUT_FILE}"
      fi
    fi
  else
    printf "%b|%b %-28s %b|%b %-40s %b|%b\n" \
      "${YELLOW}" "${RESET}" \
      "${dependency^^}" \
      "${YELLOW}" "${RESET}" \
      "${2}" \
      "${YELLOW}" "${RESET}"
  fi
}

getJavaDevVmVersion() {
  if [[ -f "/etc/versions/${image.name}.version" ]]; then
    cat "/etc/versions/${image.name}.version"
  fi
}

getUbuntuVersion() {
  grep "VERSION=" "/etc/os-release" | sed "s/.*=\"//;s/ .*//"
}

getKernelVersion() {
  uname -s -r | sed "s/.* //"
}

getKittyVersion() {
  if isPackageInstalled "kitty"; then
    kitty --version | sed "s/kitty //;s/ .*//"
  fi
}

getFirefoxVersion() {
  if isPackageInstalled "firefox"; then
    firefox --version | sed "s/.* //"
  fi
}

getBetterfoxVersion() {
  if grep -q "\* Betterfox" "${HOME}/.mozilla/firefox/"*".dev/user.js"; then
    grep -A2 "\* Betterfox" "${HOME}/.mozilla/firefox/"*".dev/user.js" | grep "version" | sed "s/.*: //;s/ .*//"
  fi
}

getIntellijIdeaVersion() {
  if [[ -d "/opt/intellij-idea" ]]; then
    jq ".version" "/opt/intellij-idea/product-info.json" | tr -d "\""
  fi
}

getDBeaverVersion() {
  if [[ -d "/opt/dbeaver" ]]; then
    grep "version=" "/opt/dbeaver/.eclipseproduct" | sed "s/.*=//"
  fi
}

getPostmanVersion() {
  if [[ -d "/opt/postman" ]]; then
    jq ".version" "/opt/postman/resources/app/package.json" | tr -d "\""
  fi
}

getKeystoreExplorerVersion() {
  if isPackageInstalled "kse"; then
    unzip -p "/opt/keystore-explorer/kse.jar" "org/kse/version.properties" | grep "KSE.Version" | sed "s/.*=//"
  fi
}

getGitVersion() {
  if isPackageInstalled "git"; then
    git version | sed "s/.*version //"
  fi
}

getGitFilterRepoVersion() {
  if [[ -f "/usr/local/bin/git-filter-repo" ]]; then
    cat "/etc/versions/git-filter-repo.version"
  fi
}

getGitLfsVersion() {
  if isPackageInstalled "git-lfs"; then
    git lfs version | sed "s/.*\///;s/ (.*//"
  fi
}

getGitHubCliVersion() {
  if isPackageInstalled "gh"; then
    gh --version | grep gh | sed "s/.*version //;s/ (.*//"
  fi
}

getJavaLtsVersion() {
  if isPackageInstalled "java"; then
    java --version | grep "java" | sed "s/java //;s/ .*//"
  fi
}

getJavaStsVersion() {
  if [[ -x "/opt/java/${jdk-sts.version}-${jdk.distribution}/bin/java" ]]; then
    /opt/java/${jdk-sts.version}-${jdk.distribution}/bin/java --version | grep "java" | sed "s/java //;s/ .*//"
  fi
}

getSDKManVersion() {
  if isPackageInstalled "sdk"; then
    cat "${HOME}/.sdkman/var/version"
  fi
}

getSDKManDependencyVersion() {
  if isPackageInstalled "sdk"; then
    local dependency="${1}"
    readlink "${HOME}/.sdkman/candidates/${dependency}/current" | sed "s/.*\///"
  fi
}

getAsyncProfilerVersion() {
  if isPackageInstalled "asprof"; then
    asprof --version | sed "s/.*profiler //;s/ .*//"
  fi
}

getKafkaVersion() {
  if [[ -d "/opt/kafka" ]]; then
    ls "/opt/kafka/libs" | grep -m 1 "kafka-server" | sed "s/.*-//;s/.jar//"
  fi
}

getNodeVersion() {
  if isPackageInstalled "node"; then
    node --version | sed "s/v//"
  fi
}

getCorepackVersion() {
  if isPackageInstalled "corepack"; then
    corepack --version
  fi
}

getNpmVersion() {
  if isPackageInstalled "npm"; then
    npm --version
  fi
}

getPnpmVersion() {
  if isPackageInstalled "pnpm"; then
    pnpm --version
  fi
}

getYarnVersion() {
  if isPackageInstalled "yarn"; then
    yarn --version
  fi
}

getGulpCliVersion() {
  if isPackageInstalled "gulp"; then
    gulp --version | grep "CLI" | sed "s/.*: //"
  fi
}

getPythonVersion() {
  if isPackageInstalled "python3"; then
    python3 --version | sed "s/.* //"
  fi
}

getPipxVersion() {
  if isPackageInstalled "pipx"; then
    pipx --version
  fi
}

getVirtualEnvVersion() {
  if isPackageInstalled "virtualenv"; then
    virtualenv --version | sed "s/virtualenv //;s/ from.*//"
  fi
}

getGoVersion() {
  if isPackageInstalled "go"; then
    go version | sed "s/.* go//;s/ .*//"
  fi
}

getDockerClientVersion() {
  if isPackageInstalled "docker"; then
    docker version --format "{{.Client.Version}}"
  fi
}

getDockerServerVersion() {
  if isPackageInstalled "docker"; then
    docker version --format "{{.Server.Version}}"
  fi
}

getDockerBuildxVersion() {
  if isPackageInstalled "docker"; then
    docker buildx version | sed "s/.* v//;s/ .*//"
  fi
}

getDockerComposeVersion() {
  if isPackageInstalled "docker"; then
    docker compose version --short
  fi
}

getDockerScoutVersion() {
  if isPackageInstalled "docker"; then
    docker scout version | grep version | sed "s/.* v//;s/ (.*//"
  fi
}

getKubectlClientVersion() {
  if isPackageInstalled "kubectl"; then
    kubectl version --client | grep "Client Version:" | sed "s/.*v//"
  fi
}

getKubectlServerVersion() {
  if isPackageInstalled "k3d"; then
    k3d version | grep "k3s" | sed "s/.*v//;s/ (.*//"
  fi
}

getKubectlKrewVersion() {
  if [[ -d "${HOME}/.krew" ]]; then
    kubectl krew version | grep "GitTag" | sed "s/.*v//"
  fi
}

getK3dVersion() {
  if isPackageInstalled "k3d"; then
    k3d version | grep "k3d" | sed "s/.*v//"
  fi
}

getHelmVersion() {
  if isPackageInstalled "helm"; then
    helm version --template="Version: {{.Version}}" | sed "s/.*v//"
  fi
}

isPackageInstalled() {
  local package="${1}"
  command -v "${package}" >/dev/null
}

main
