#!/bin/bash -i
# DISPLAY DEPENDENCY VERSIONS INSTALLED ON THE SYSTEM

set -o errexit  # ABORT ON NON-ZERO EXIT STATUS
set -o pipefail # DON'T HIDE ERRORS WITHIN PIPES

# CONSTANTS
readonly ARGS=( "${@}" )
readonly SEPARATOR=$(printf "%.s#" {1..75})
# COLORS
readonly RESET="\033[0m"
readonly GREEN="\033[1;32m"
readonly YELLOW="\033[1;33m"

main() {
  options "${ARGS[@]}"
  logSection "SYSTEM"
  logVersion "JAVA DEV VM" "$(getJavaDevVmVersion)"
  logVersion "UBUNTU" "$(getUbuntuVersion)"
  logVersion "KERNEL" "$(getKernelVersion)"
  logVersion "KITTY TERMINAL" "$(getKittyVersion)"
  logVersion "FIREFOX" "$(getFirefoxVersion)"
  logSection "APPS"
  logVersion "INTELLIJ IDEA" "$(getIntellijIdeaVersion)"
  logVersion "DBEAVER" "$(getDBeaverVersion)"
  logVersion "POSTMAN" "$(getPostmanVersion)"
  logVersion "KEYSTORE EXPLORER" "$(getKeystoreExplorerVersion)"
  logSection "VERSION CONTROL"
  logVersion "GIT" "$(getGitVersion)"
  logVersion "GIT FILTER-REPO" "$(getGitFilterRepoVersion)"
  logVersion "GIT LFS" "$(getGitLfsVersion)"
  logVersion "GITHUB CLI" "$(getGitHubCliVersion)"
  logSection "JAVA"
  logVersion "SDKMAN" "$(getSdkManVersion)"
  logVersion "JAVA" "$(getSdkManDependencyVersion "java")"
  logVersion "MAVEN" "$(getSdkManDependencyVersion "maven")"
  logVersion "SPRING BOOT CLI" "$(getSdkManDependencyVersion "springboot")"
  logVersion "ASYNC PROFILER" "$(getAsyncProfilerVersion)"
  logVersion "KAFKA" "$(getKafkaVersion)"
  logSection "JAVASCRIPT"
  logVersion "NODE" "$(getNodeVersion)"
  logVersion "COREPACK" "$(getCorepackVersion)"
  logVersion "NPM" "$(getNpmVersion)"
  logVersion "PNPM" "$(getPnpmVersion)"
  logVersion "YARN" "$(getYarnVersion)"
  logVersion "GULP CLI" "$(getGulpCliVersion)"
  logSection "PYTHON"
  logVersion "PYTHON" "$(getPythonVersion)"
  logVersion "PIPX" "$(getPipxVersion)"
  logVersion "VIRTUALENV" "$(getVirtualEnvVersion)"
  logSection "CLOUD"
  logVersion "GO" "$(getGoVersion)"
  logVersion "DOCKER CLIENT" "$(getDockerClientVersion)"
  logVersion "DOCKER SERVER" "$(getDockerServerVersion)"
  logVersion "DOCKER BUILDX" "$(getDockerBuildxVersion)"
  logVersion "DOCKER COMPOSE" "$(getDockerComposeVersion)"
  logVersion "DOCKER SCOUT" "$(getDockerScoutVersion)"
  logVersion "KUBECTL CLIENT" "$(getKubectlClientVersion)"
  logVersion "KUBECTL SERVER" "$(getKubectlServerVersion)"
  logVersion "KUBECTL KREW" "$(getKubectlKrewVersion)"
  logVersion "K3D" "$(getK3dVersion)"
  logVersion "HELM" "$(getHelmVersion)"
  logSeparator
}

options() {
  while (( ${#} > 0 )); do
    case "${1}" in
      *) help;;
    esac
    shift
  done
}

help() {
  cat << EOF
Usage: ${0}

Display dependency versions installed on the system
EOF
  exit 1
}

logSection() {
  local sectionName="${1}"
  logSeparator
  printf "%b#%b %b%-71s%b %b#%b\n" \
    "${YELLOW}" "${RESET}" \
    "${GREEN}" "${sectionName}" "${RESET}"\
    "${YELLOW}" "${RESET}"
  logSeparator
}

logSeparator() {
  printf "%b%s%b\n" "${YELLOW}" "${SEPARATOR}" "${RESET}"
}

logVersion() {
  printf "%b|%b %-28s %b|%b %-40s %b|%b\n" \
    "${YELLOW}" "${RESET}" \
    "${1}" \
    "${YELLOW}" "${RESET}" \
    "${2}" \
    "${YELLOW}" "${RESET}"
}

getJavaDevVmVersion() {
  [[ -f "/etc/versions/java-dev-vm.version" ]] \
    && cat "/etc/versions/java-dev-vm.version"
}

getUbuntuVersion() {
  grep "VERSION=" "/etc/os-release" | sed "s/.*=\"//;s/ .*//"
}

getKernelVersion() {
  uname -s -r | sed "s/.* //"
}

getKittyVersion() {
  isPackageInstalled "kitty" \
    && kitty --version | sed "s/kitty //;s/ .*//"
}

getFirefoxVersion() {
  isPackageInstalled "firefox" \
    && firefox --version | sed "s/.* //"
}

getIntellijIdeaVersion() {
  [[ -d "/opt/intellij-idea" ]] \
    && jq ".version" "/opt/intellij-idea/product-info.json" | tr -d "\""
}

getDBeaverVersion() {
  [[ -d "/opt/dbeaver" ]] \
    && grep "version=" "/opt/dbeaver/.eclipseproduct" | sed "s/.*=//"
}

getPostmanVersion() {
  [[ -d "/opt/postman" ]] \
    && jq ".version" "/opt/postman/resources/app/package.json" | tr -d "\""
}

getKeystoreExplorerVersion() {
  isPackageInstalled "kse" \
    && unzip -p "/opt/keystore-explorer/kse.jar" "org/kse/version.properties" | grep "KSE.Version" | sed "s/.*=//"
}

getGitVersion() {
  isPackageInstalled "git" \
    && git version | sed "s/.*version //"
}

getGitFilterRepoVersion() {
  [[ -f "/usr/local/bin/git-filter-repo" ]] \
    && cat "/etc/versions/git-filter-repo.version"
}

getGitLfsVersion() {
  isPackageInstalled "git-lfs" \
    && git lfs version | sed "s/.*\///;s/ (.*//"
}

getGitHubCliVersion() {
  isPackageInstalled "gh" \
    && gh --version | grep gh | sed "s/.*version //;s/ (.*//"
}

getSdkManVersion() {
  isPackageInstalled "sdk" \
    && cat "${HOME}/.sdkman/var/version"
}

getSdkManDependencyVersion() {
  if isPackageInstalled "sdk"; then
    local dependency="${1}"
    readlink "${HOME}/.sdkman/candidates/${dependency}/current"
  fi
}

getAsyncProfilerVersion() {
  isPackageInstalled "asprof" \
      && asprof --version | sed "s/.*profiler //;s/ .*//"
}

getKafkaVersion() {
  [[ -d "/opt/kafka" ]] \
    && ls "/opt/kafka/libs" | grep -m 1 "kafka-server" | sed "s/.*-//;s/.jar//"
}

getNodeVersion() {
  isPackageInstalled "node" \
    && node --version | sed "s/v//"
}

getCorepackVersion() {
  isPackageInstalled "corepack" \
    && corepack --version
}

getNpmVersion() {
  isPackageInstalled "npm" \
    && npm --version
}

getPnpmVersion() {
  isPackageInstalled "pnpm" \
    && pnpm --version
}

getYarnVersion() {
  isPackageInstalled "yarn" \
    && yarn --version
}

getGulpCliVersion() {
  isPackageInstalled "gulp" \
    && gulp --version | grep "CLI" | sed "s/.*: //"
}

getPythonVersion() {
  isPackageInstalled "python3" \
    && python3 --version | sed "s/.* //"
}

getPipxVersion() {
  isPackageInstalled "pipx" \
    && pipx --version
}

getVirtualEnvVersion() {
  isPackageInstalled "virtualenv" \
    && virtualenv --version | sed "s/virtualenv //;s/ from.*//"
}

getGoVersion() {
  isPackageInstalled "go" \
    && go version | sed "s/.* go//;s/ .*//"
}

getDockerClientVersion() {
  isPackageInstalled "docker" \
    && docker version --format "{{.Client.Version}}"
}

getDockerServerVersion() {
  isPackageInstalled "docker" \
    && docker version --format "{{.Server.Version}}"
}

getDockerBuildxVersion() {
  isPackageInstalled "docker" \
    && docker buildx version | sed "s/.* v//;s/ .*//"
}

getDockerComposeVersion() {
  isPackageInstalled "docker" \
    && docker compose version --short
}

getDockerScoutVersion() {
  isPackageInstalled "docker" \
    && docker scout version | grep version | sed "s/.* v//;s/ (.*//"
}

getKubectlClientVersion() {
  isPackageInstalled "kubectl" \
    && kubectl version --client | grep "Client Version:" | sed "s/.*v//"
}

getKubectlServerVersion() {
  isPackageInstalled "k3d" \
    && k3d version | grep "k3s" | sed "s/.*v//;s/ (.*//"
}

getKubectlKrewVersion() {
  [[ -d "${HOME}/.krew" ]] \
    && kubectl krew version | grep "GitTag" | sed "s/.*v//"
}

getK3dVersion() {
  isPackageInstalled "k3d" \
    && k3d version | grep "k3d" | sed "s/.*v//"
}

getHelmVersion() {
  isPackageInstalled "helm" \
    && helm version --template="Version: {{.Version}}" | sed "s/.*v//"
}

isPackageInstalled() {
  local package="${1}"
  command -v "${package}" >/dev/null
}

main
