name: Attestation Verification

on:
  workflow_run:
    workflows: [ "Build, Test and Push Images" ]
    types:
      - completed
  schedule:
    - cron: "30 5 * * *"

jobs:
  main:
    name: Attestation Verification
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract properties
        run: |
          echo "IMAGE_NAMESPACE=$(mvn help:evaluate -Dexpression=image.namespace -q -DforceStdout)" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=$(mvn help:evaluate -Dexpression=image.name -q -DforceStdout)" >> ${GITHUB_ENV}
          echo "IMAGE_VERSION=$(mvn help:evaluate -Dexpression=image.version -q -DforceStdout)" >> ${GITHUB_ENV}
      - name: Generate Workflow Stats
        run: |
          echo "### Workflow Stats" >> ${GITHUB_STEP_SUMMARY}
          echo "- GitHub CLI **$(gh --version | grep gh | sed "s/.*version //;s/ (.*//")**" >> ${GITHUB_STEP_SUMMARY}
          echo "### More information" >> ${GITHUB_STEP_SUMMARY}
          echo "- [Verifying Provenance and SBOM Attestations](https://github.com/${GITHUB_REPOSITORY_OWNER}/${IMAGE_NAME}/blob/main/docs/provenance-and-sbom.md)" >> ${GITHUB_STEP_SUMMARY}
      - name: Verify Community Image
        run: |
          gh attestation verify oci://docker.io/${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}-community --owner "${GITHUB_REPOSITORY_OWNER}"
      - name: Verify Provenance attached to Community Image
        run: |
          docker buildx imagetools inspect ${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}-community \
            --format "{{ json .Provenance.SLSA }}" | grep -q "github.com/${GITHUB_REPOSITORY_OWNER}"
      - name: Verify SBOM attached to Community Image
        run: |
          docker buildx imagetools inspect ${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}-community \
            --format "{{ json .SBOM.SPDX }}" | grep -q "/opt/java"
      - name: Verify Ultimate Image
        run: |
          gh attestation verify oci://docker.io/${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}-ultimate --owner "${GITHUB_REPOSITORY_OWNER}"
      - name: Verify Provenance attached to Ultimate Image
        run: |
          docker buildx imagetools inspect ${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}-ultimate \
            --format "{{ json .Provenance.SLSA }}" | grep -q "github.com/${GITHUB_REPOSITORY_OWNER}"
      - name: Verify SBOM attached to Ultimate Image
        run: |
          docker buildx imagetools inspect ${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}-ultimate \
            --format "{{ json .SBOM.SPDX }}" | grep -q "/opt/java"
