name: Build and Push Images

on:
  release:
    types: [published]

jobs:
  build_and_push_images:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set up Oracle JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21.0.4
          distribution: oracle
          cache: maven
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push -community Image
        run: mvn clean package -B -Pcommunity,github-actions
      - name: Build and Push -ultimate Image
        run: mvn clean package -B -Pultimate,github-actions,prune-builder
